services:
  haproxy:
    image: haproxy-with-minica/haproxy
    build:
      context: ./haproxy
    ports:
      - target: 80
        host_ip: 127.0.0.1
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        host_ip: 127.0.0.1
        published: 443
        protocol: tcp
        mode: host
    depends_on:
      - sample
  sample:
    image: haproxy-with-minica/sample
    build:
      context: ./sample/.devcontainer
      args:
        - VARIANT=16-bullseye
    volumes:
      - .:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
